name: 报告Bug
description: 报告APP运行时出现的问题
title: "[Bug]: "
labels: ["bug🐞"]
body:
  - type: markdown
    attributes:
      value: |
        感谢报告问题, 请先补全标题后填写以下信息
  - type: textarea
    id: what-happened
    attributes:
      label: 描述
      description: 描述问题
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: 使用的APP版本
      value: "latest"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 使用的操作系统
      multiple: true
      options:
        - Android
        - iOS
        - Windows
        - other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 日志
      description: 上传日志, 在设置-logs中, 点击右上角的菜单后, 点击导出日志; 或者将错误相关日志粘贴到这里
  - type: textarea
    id: screenshotOrVideo
    attributes:
      label: 截图或视频
      description: 在这里上传相关的屏幕截图或者视频