name: Build IOS
run-name: Build IOS
on:
  workflow_dispatch: {}
jobs:
  Build_IOS:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app
    - run: flutter pub get
    - run: flutter build ios --debug --no-codesign
    - run: cd ios
    - run:
        xcodebuild -workspace Runner.xcworkspace -scheme Runner -config Flutter/Release.xcconfig -derivedDataPath "../build/ios_integ" -sdk iphonesimulator -configuration Debug
    - uses: actions/upload-artifact@v3
      with:
        name: build_files
        path: /Users/runner/work/PicaComic/PicaComic/build/ios_integ
